"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  RedirectToSignIn,
} from "@clerk/nextjs";
import { usePathname } from "next/navigation";
import { AppBar, Toolbar, Typography, Button } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const publicPages = ["/"];

export default function RootLayout({ children }) {
  const router = usePathname();
  const isPublicPage = publicPages.includes(router);

  console.log("Current Pathname:", usePathname()); // Debugging the pathname
  console.log("Is Public Page:", isPublicPage); // Debugging the public page check

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" style={{ flexGrow: 1 }}>
                <a
                  href="/"
                  style={{ color: "inherit", textDecoration: "none" }}
                >
                  Flashcard SaaS
                </a>
              </Typography>
              <SignedOut>
                <Button color="inherit">
                  <SignInButton mode="modal" />
                </Button>
                <Button color="inherit">
                  <SignUpButton mode="modal" />
                </Button>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </Toolbar>
          </AppBar>
          {isPublicPage ? (
            children
          ) : (
            <>
              <SignedIn>{children}</SignedIn>
              <SignedOut>
                <RedirectToSignIn />
              </SignedOut>
            </>
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}
